### ISSUE TITLE
request for pull request!

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [astorfi/CNTK-World#1]
Hi

Good job. It seems currently CNTK suffers from lack of developers, examples and some model zoo. I decided to do something similar to this repo but you are being ahead of me. Far ahead!

Please check [cntk_examples](https://github.com/hajix/cntk_examples) repo and tell me if you are willing to these examples in your cntk-world repo. I also planned to release a RNNLM in the near future.

best regards

**Comment by astorfi** [comment]
@hajix Thanks for attention and kind words. It would be more than great if we can collaborate on that. Please contact me via email and we continue the conversation over there. My email is available in the [CONTRIBUTING](https://github.com/astorfi/CNTK-World/blob/master/CONTRIBUTING.rst) section.

Bests
